"""Added max count tryies get memes to user

Revision ID: 9ea30b169ae9
Revises: 09fd2e36a0b0
Create Date: 2026-02-26 18:09:16.949113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea30b169ae9'
down_revision: Union[str, Sequence[str], None] = '09fd2e36a0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('daily_count_max_memes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'daily_count_max_memes')
    # ### end Alembic commands ###
