"""Added subscription to user

Revision ID: 61d95e3ec498
Revises: a96adb1ef2fd
Create Date: 2026-02-25 21:05:04.939844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d95e3ec498'
down_revision: Union[str, Sequence[str], None] = 'a96adb1ef2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name=op.f('fk_user_subscription_subscription_id_subscription')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_subscription_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_subscription')),
    sa.UniqueConstraint('user_id', 'subscription_id', name=op.f('uq_user_subscription_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscription')
    # ### end Alembic commands ###
