"""Created base entities

Revision ID: 84668336a838
Revises: 
Create Date: 2026-02-19 22:14:52.359121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84668336a838'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content')),
    sa.UniqueConstraint('path', name=op.f('uq_content_path'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daily_count', sa.Integer(), nullable=False),
    sa.Column('timestamp_first_count', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_user_telegram_id'))
    )
    op.create_table('view_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name=op.f('fk_view_content_content_id_content')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_view_content_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_view_content')),
    sa.UniqueConstraint('user_id', 'content_id', name=op.f('uq_view_content_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('view_content')
    op.drop_table('user')
    op.drop_table('content')
    # ### end Alembic commands ###
