"""Added subscription

Revision ID: a96adb1ef2fd
Revises: a3acdea84141
Create Date: 2026-02-25 18:01:31.984412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96adb1ef2fd'
down_revision: Union[str, Sequence[str], None] = 'a3acdea84141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('period', sa.JSON(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription')),
    sa.UniqueConstraint('plan', name=op.f('uq_subscription_plan'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    # ### end Alembic commands ###
