"""Added type to content

Revision ID: a3acdea84141
Revises: 8f578a2c084d
Create Date: 2026-02-23 22:07:01.133095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3acdea84141'
down_revision: Union[str, Sequence[str], None] = '8f578a2c084d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'type')
    # ### end Alembic commands ###
